### PUT updates patient entity
PUT localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.dqoe2@example.com",
  "address": "50Cheeky streeet",
  "dateOfBirth": "1995-09-09"
}

###